# Site settings
title: Shear Sherrie
email: shear.sherri3@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Shear Sherrie is a licensed hair & makeup artist serving the St. Louis, MO metro area and beyond. Services include Hair color, highlights, bombshell blondes, Victoria Secret inspired balayage, SoCAP & Perfectress Extensions, trendy hair cuts, blowout styles, heated styles, smoothing treatments, deep conditioning love, men's cuts, facial waxing, and otraditional & airbrush makeup.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://shearsherrie.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  larryboymi

# Build settings
markdown: kramdown


paginate: 4
paginate_path: "blog/page:num"